### ISSUE TITLE
Limit.

### ISSUE THREAD

**Issue by jinkazph** [Py-KMS-Organization/py-kms#104]
Hi, is there a limit of how many computer I can activated? ty

**Comment by didotb** [comment]
According to Microsoft's documentation on KMS Activation:
> KMS can activate physical and virtual computers, but to qualify for KMS activation, a network must have a minimum number of computers (called the activation threshold). KMS clients activate only after this threshold is met. To ensure that the activation threshold is met, a KMS host counts the number of computers that are requesting activation on the network.
> 
> KMS hosts count the most recent connections. When a client or server contacts the KMS host, the host adds the machine ID to its count and then returns the current count value in its response. The client or server will activate if the count is high enough. Clients will activate if the count is 25 or higher. Servers and volume editions of Microsoft Office products will activate if the count is five or greater. The KMS only counts unique connections from the past 30 days, and only stores the 50 most recent contacts.

Seems like the only limit is the `minimum number of computers`. However, since you can set that option up in this emulator, you don't really need to physically have that amount of computers in-order to start activating them.

[Source](https://learn.microsoft.com/en-us/windows-server/get-started/kms-activation-planning)
