### ISSUE TITLE
Using Google Colab and ngrok to serve it temporarily

### ISSUE THREAD

**Issue by kryptoniancode** [Py-KMS-Organization/py-kms#80]
I have tried following to serve and activate using ngrok in google colab but I am not getting it work. I have changed http to tcp.

# Setup Google Colab
1. Visit https://colab.research.google.com/
2. Sign in / Sign up using google account
3. Create new note book

### Get authorised ngrok tunnel
1. Download ngrok Google Colab
```
!wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
```

2. Unzip
```
!unzip ngrok-stable-linux-amd64.zip
```

3. Sign up at ngrok and get authtoke
```
!./ngrok authtoken <your-auth-token>
```

5. Start ngrok and python kms server

```
!./ngrok tcp 8081 & python3 /content/py-kms/py-kms/pykms_Server.py 0.0.0.0 8081
```

Thanks for maintaining the project

**Comment by kryptoniancode** [comment]
Activated successfully using `tcp`

1. Run kms server and tunnel it
```
!./ngrok tcp 8081 & python3 /content/py-kms/py-kms/pykms_Server.py 0.0.0.0 8081
```

2. Goto ngrok dashboard and get tcp address, https://dashboard.ngrok.com/tunnels/agents/

3. Set host and port and activate
```
/sethst:4.tcp.ngrok.io
/setprt:11785
/act
```
![image](https://user-images.githubusercontent.com/119998820/206281117-543be6c8-15df-4508-8a7e-353a7f4a76ec.png)

## Result
### Colab
![image](https://user-images.githubusercontent.com/119998820/206280759-925cc697-bb1f-439e-9436-b4b346a4a70e.png)

### CMD
![image](https://user-images.githubusercontent.com/119998820/206281425-0272061b-6efe-4da8-bd53-c6e4a22bbe01.png)

**Comment by Matthew-Beckett** [comment]
@simonmicro can you close this as resolved and also give me permission to close issues?

**Comment by Matthew-Beckett** [comment]
Hi, I think this is because you've configured Ngrok as a HTTP tunnel and as a result, Ngrok is attempting to terminate and re-establish a HTTP connection to an RPC service running on a plain TCP port. I think you should be able to resolve this by running `ngrok tcp 1688`. Thanks,Matt07.12.2022, 19:12, "kryptoniancode" ***@***.***>:
I have tried following to serve and activate using ngrok in google colab but I am not getting it work.
Setup Google Colab

Visit https://colab.research.google.com/
Sign in / Sign up using google account
Create new note book

Install and run ngrok

Intall

!pip install pyngrok==4.1.1


Get tunnel using ngrok

from pyngrok import ngrok
public_url = ngrok.connect(port='8000')
print (public_url)


Run python kms server

!python3 /content/py-kms/py-kms/pykms_Server.py 0.0.0.0 8000

Error
These are following errors in ngrok, google colab and activating office
google colab
This errors come when the link opened in browser.

ngrok
When opening the url in browser.

office
Note: In above image Invalid RPC request type 84. come from browser when url opened in browser. When setting the url as ngrok using sethst does nothing.

Following can also be done to get authorised ngrok tunnel

Download ngrok Google Colab

!wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip


Unzip

!unzip ngrok-stable-linux-amd64.zip


Sign up at ngrok and get authtoke

!./ngrok config add-authtoken <your-auth-token>


Start ngrok and python kms server

!python3 pykms_Server.py 0.0.0.0 1688 & ngrok http 1688

If above issues can be resolved then it be easier activate lower end devices without installing docker, virtual machine, wsl2 etc.
Thanks for maintaining the project

**Comment by kryptoniancode** [comment]
@Matthew-Beckett  Thanks

**Comment by simonmicro** [comment]
@Matthew-Beckett Consider it done :)
